/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface CreateLotteryData {
    lotteryType: LotteryType;
    ticketsPerUserMax: bigint;
    logo?: ExternalBlob;
    name: string;
    firstPrizeRatio: bigint;
    description: string;
    drawTime: Time;
    firstPrizePercent: bigint;
    thirdPrizePercent: bigint;
    maxTickets: bigint;
    secondPrizeRatio: bigint;
    secondPrizePercent: bigint;
    winnerPayoutPercent: bigint;
    ticketPrice: bigint;
    thirdPrizeRatio: bigint;
    drawInterval: DrawInterval;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface LotteryPool {
    id: string;
    status: LotteryStatus;
    totalTicketsSold: bigint;
    lotteryType: LotteryType;
    ticketsPerUserMax: bigint;
    logo?: ExternalBlob;
    name: string;
    createdAt: Time;
    firstPrizeRatio: bigint;
    description: string;
    drawTime: Time;
    firstPrizePercent: bigint;
    thirdPrizePercent: bigint;
    maxTickets: bigint;
    secondPrizeRatio: bigint;
    secondPrizePercent: bigint;
    totalPoolAmount: bigint;
    winnerPayoutPercent: bigint;
    ticketPrice: bigint;
    thirdPrizeRatio: bigint;
    drawInterval: DrawInterval;
}
export interface UserProfile {
    id: string;
    referralCode: string;
    isBlocked: boolean;
    name: string;
    createdAt: Time;
    role: string;
    blockedAt?: Time;
    email: string;
    coinsBalance: bigint;
    isVerified: boolean;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum CreateLotteryError {
    invalidTicketConfig = "invalidTicketConfig",
    invalidPrizeConfig = "invalidPrizeConfig",
    invalidDrawTime = "invalidDrawTime",
    unauthorized = "unauthorized"
}
export enum DrawInterval {
    h1 = "h1",
    h3 = "h3",
    h5 = "h5",
    h12 = "h12",
    daily = "daily",
    weekly = "weekly"
}
export enum LotteryStatus {
    active = "active",
    cancelled = "cancelled",
    completed = "completed"
}
export enum LotteryType {
    daily = "daily",
    weekly = "weekly"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_notFound_unauthorized {
    notFound = "notFound",
    unauthorized = "unauthorized"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createLottery(data: CreateLotteryData): Promise<{
        __kind__: "ok";
        ok: LotteryPool;
    } | {
        __kind__: "err";
        err: CreateLotteryError;
    }>;
    getCallerUserProfile(): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: Variant_notFound_unauthorized;
    }>;
    getCallerUserRole(): Promise<UserRole>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { CreateLotteryData as _CreateLotteryData, CreateLotteryError as _CreateLotteryError, DrawInterval as _DrawInterval, ExternalBlob as _ExternalBlob, LotteryPool as _LotteryPool, LotteryStatus as _LotteryStatus, LotteryType as _LotteryType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createLottery(arg0: CreateLotteryData): Promise<{
        __kind__: "ok";
        ok: LotteryPool;
    } | {
        __kind__: "err";
        err: CreateLotteryError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createLottery(await to_candid_CreateLotteryData_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLottery(await to_candid_CreateLotteryData_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: Variant_notFound_unauthorized;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_variant_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_CreateLotteryError_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateLotteryError): CreateLotteryError {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_DrawInterval_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DrawInterval): DrawInterval {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_LotteryPool_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LotteryPool): Promise<LotteryPool> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_LotteryStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LotteryStatus): LotteryStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_LotteryType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LotteryType): LotteryType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _LotteryStatus;
    totalTicketsSold: bigint;
    lotteryType: _LotteryType;
    ticketsPerUserMax: bigint;
    logo: [] | [_ExternalBlob];
    name: string;
    createdAt: _Time;
    firstPrizeRatio: bigint;
    description: string;
    drawTime: _Time;
    firstPrizePercent: bigint;
    thirdPrizePercent: bigint;
    maxTickets: bigint;
    secondPrizeRatio: bigint;
    secondPrizePercent: bigint;
    totalPoolAmount: bigint;
    winnerPayoutPercent: bigint;
    ticketPrice: bigint;
    thirdPrizeRatio: bigint;
    drawInterval: _DrawInterval;
}): Promise<{
    id: string;
    status: LotteryStatus;
    totalTicketsSold: bigint;
    lotteryType: LotteryType;
    ticketsPerUserMax: bigint;
    logo?: ExternalBlob;
    name: string;
    createdAt: Time;
    firstPrizeRatio: bigint;
    description: string;
    drawTime: Time;
    firstPrizePercent: bigint;
    thirdPrizePercent: bigint;
    maxTickets: bigint;
    secondPrizeRatio: bigint;
    secondPrizePercent: bigint;
    totalPoolAmount: bigint;
    winnerPayoutPercent: bigint;
    ticketPrice: bigint;
    thirdPrizeRatio: bigint;
    drawInterval: DrawInterval;
}> {
    return {
        id: value.id,
        status: from_candid_LotteryStatus_n20(_uploadFile, _downloadFile, value.status),
        totalTicketsSold: value.totalTicketsSold,
        lotteryType: from_candid_LotteryType_n22(_uploadFile, _downloadFile, value.lotteryType),
        ticketsPerUserMax: value.ticketsPerUserMax,
        logo: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.logo)),
        name: value.name,
        createdAt: value.createdAt,
        firstPrizeRatio: value.firstPrizeRatio,
        description: value.description,
        drawTime: value.drawTime,
        firstPrizePercent: value.firstPrizePercent,
        thirdPrizePercent: value.thirdPrizePercent,
        maxTickets: value.maxTickets,
        secondPrizeRatio: value.secondPrizeRatio,
        secondPrizePercent: value.secondPrizePercent,
        totalPoolAmount: value.totalPoolAmount,
        winnerPayoutPercent: value.winnerPayoutPercent,
        ticketPrice: value.ticketPrice,
        thirdPrizeRatio: value.thirdPrizeRatio,
        drawInterval: from_candid_DrawInterval_n26(_uploadFile, _downloadFile, value.drawInterval)
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    referralCode: string;
    isBlocked: boolean;
    name: string;
    createdAt: _Time;
    role: string;
    blockedAt: [] | [_Time];
    email: string;
    coinsBalance: bigint;
    isVerified: boolean;
}): {
    id: string;
    referralCode: string;
    isBlocked: boolean;
    name: string;
    createdAt: Time;
    role: string;
    blockedAt?: Time;
    email: string;
    coinsBalance: bigint;
    isVerified: boolean;
} {
    return {
        id: value.id,
        referralCode: value.referralCode,
        isBlocked: value.isBlocked,
        name: value.name,
        createdAt: value.createdAt,
        role: value.role,
        blockedAt: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.blockedAt)),
        email: value.email,
        coinsBalance: value.coinsBalance,
        isVerified: value.isVerified
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _LotteryPool;
} | {
    err: _CreateLotteryError;
}): Promise<{
    __kind__: "ok";
    ok: LotteryPool;
} | {
    __kind__: "err";
    err: CreateLotteryError;
}> {
    return "ok" in value ? {
        __kind__: "ok",
        ok: await from_candid_LotteryPool_n18(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_CreateLotteryError_n28(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    completed: null;
}): LotteryStatus {
    return "active" in value ? LotteryStatus.active : "cancelled" in value ? LotteryStatus.cancelled : "completed" in value ? LotteryStatus.completed : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    daily: null;
} | {
    weekly: null;
}): LotteryType {
    return "daily" in value ? LotteryType.daily : "weekly" in value ? LotteryType.weekly : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    h1: null;
} | {
    h3: null;
} | {
    h5: null;
} | {
    h12: null;
} | {
    daily: null;
} | {
    weekly: null;
}): DrawInterval {
    return "h1" in value ? DrawInterval.h1 : "h3" in value ? DrawInterval.h3 : "h5" in value ? DrawInterval.h5 : "h12" in value ? DrawInterval.h12 : "daily" in value ? DrawInterval.daily : "weekly" in value ? DrawInterval.weekly : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invalidTicketConfig: null;
} | {
    invalidPrizeConfig: null;
} | {
    invalidDrawTime: null;
} | {
    unauthorized: null;
}): CreateLotteryError {
    return "invalidTicketConfig" in value ? CreateLotteryError.invalidTicketConfig : "invalidPrizeConfig" in value ? CreateLotteryError.invalidPrizeConfig : "invalidDrawTime" in value ? CreateLotteryError.invalidDrawTime : "unauthorized" in value ? CreateLotteryError.unauthorized : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: {
        notFound: null;
    } | {
        unauthorized: null;
    };
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: Variant_notFound_unauthorized;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n31(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_variant_n34(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notFound: null;
} | {
    unauthorized: null;
}): Variant_notFound_unauthorized {
    return "notFound" in value ? Variant_notFound_unauthorized.notFound : "unauthorized" in value ? Variant_notFound_unauthorized.unauthorized : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function to_candid_CreateLotteryData_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateLotteryData): Promise<_CreateLotteryData> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_DrawInterval_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DrawInterval): _DrawInterval {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_LotteryType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LotteryType): _LotteryType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lotteryType: LotteryType;
    ticketsPerUserMax: bigint;
    logo?: ExternalBlob;
    name: string;
    firstPrizeRatio: bigint;
    description: string;
    drawTime: Time;
    firstPrizePercent: bigint;
    thirdPrizePercent: bigint;
    maxTickets: bigint;
    secondPrizeRatio: bigint;
    secondPrizePercent: bigint;
    winnerPayoutPercent: bigint;
    ticketPrice: bigint;
    thirdPrizeRatio: bigint;
    drawInterval: DrawInterval;
}): Promise<{
    lotteryType: _LotteryType;
    ticketsPerUserMax: bigint;
    logo: [] | [_ExternalBlob];
    name: string;
    firstPrizeRatio: bigint;
    description: string;
    drawTime: _Time;
    firstPrizePercent: bigint;
    thirdPrizePercent: bigint;
    maxTickets: bigint;
    secondPrizeRatio: bigint;
    secondPrizePercent: bigint;
    winnerPayoutPercent: bigint;
    ticketPrice: bigint;
    thirdPrizeRatio: bigint;
    drawInterval: _DrawInterval;
}> {
    return {
        lotteryType: to_candid_LotteryType_n12(_uploadFile, _downloadFile, value.lotteryType),
        ticketsPerUserMax: value.ticketsPerUserMax,
        logo: value.logo ? candid_some(await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.logo)) : candid_none(),
        name: value.name,
        firstPrizeRatio: value.firstPrizeRatio,
        description: value.description,
        drawTime: value.drawTime,
        firstPrizePercent: value.firstPrizePercent,
        thirdPrizePercent: value.thirdPrizePercent,
        maxTickets: value.maxTickets,
        secondPrizeRatio: value.secondPrizeRatio,
        secondPrizePercent: value.secondPrizePercent,
        winnerPayoutPercent: value.winnerPayoutPercent,
        ticketPrice: value.ticketPrice,
        thirdPrizeRatio: value.thirdPrizeRatio,
        drawInterval: to_candid_DrawInterval_n15(_uploadFile, _downloadFile, value.drawInterval)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    referralCode: string;
    isBlocked: boolean;
    name: string;
    createdAt: Time;
    role: string;
    blockedAt?: Time;
    email: string;
    coinsBalance: bigint;
    isVerified: boolean;
}): {
    id: string;
    referralCode: string;
    isBlocked: boolean;
    name: string;
    createdAt: _Time;
    role: string;
    blockedAt: [] | [_Time];
    email: string;
    coinsBalance: bigint;
    isVerified: boolean;
} {
    return {
        id: value.id,
        referralCode: value.referralCode,
        isBlocked: value.isBlocked,
        name: value.name,
        createdAt: value.createdAt,
        role: value.role,
        blockedAt: value.blockedAt ? candid_some(value.blockedAt) : candid_none(),
        email: value.email,
        coinsBalance: value.coinsBalance,
        isVerified: value.isVerified
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LotteryType): {
    daily: null;
} | {
    weekly: null;
} {
    return value == LotteryType.daily ? {
        daily: null
    } : value == LotteryType.weekly ? {
        weekly: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DrawInterval): {
    h1: null;
} | {
    h3: null;
} | {
    h5: null;
} | {
    h12: null;
} | {
    daily: null;
} | {
    weekly: null;
} {
    return value == DrawInterval.h1 ? {
        h1: null
    } : value == DrawInterval.h3 ? {
        h3: null
    } : value == DrawInterval.h5 ? {
        h5: null
    } : value == DrawInterval.h12 ? {
        h12: null
    } : value == DrawInterval.daily ? {
        daily: null
    } : value == DrawInterval.weekly ? {
        weekly: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
