/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LotteryType = IDL.Variant({
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const DrawInterval = IDL.Variant({
  'h1' : IDL.Null,
  'h3' : IDL.Null,
  'h5' : IDL.Null,
  'h12' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const CreateLotteryData = IDL.Record({
  'lotteryType' : LotteryType,
  'ticketsPerUserMax' : IDL.Nat,
  'logo' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'firstPrizeRatio' : IDL.Nat,
  'description' : IDL.Text,
  'drawTime' : Time,
  'firstPrizePercent' : IDL.Nat,
  'thirdPrizePercent' : IDL.Nat,
  'maxTickets' : IDL.Nat,
  'secondPrizeRatio' : IDL.Nat,
  'secondPrizePercent' : IDL.Nat,
  'winnerPayoutPercent' : IDL.Nat,
  'ticketPrice' : IDL.Nat,
  'thirdPrizeRatio' : IDL.Nat,
  'drawInterval' : DrawInterval,
});
export const LotteryStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const LotteryPool = IDL.Record({
  'id' : IDL.Text,
  'status' : LotteryStatus,
  'totalTicketsSold' : IDL.Nat,
  'lotteryType' : LotteryType,
  'ticketsPerUserMax' : IDL.Nat,
  'logo' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'createdAt' : Time,
  'firstPrizeRatio' : IDL.Nat,
  'description' : IDL.Text,
  'drawTime' : Time,
  'firstPrizePercent' : IDL.Nat,
  'thirdPrizePercent' : IDL.Nat,
  'maxTickets' : IDL.Nat,
  'secondPrizeRatio' : IDL.Nat,
  'secondPrizePercent' : IDL.Nat,
  'totalPoolAmount' : IDL.Nat,
  'winnerPayoutPercent' : IDL.Nat,
  'ticketPrice' : IDL.Nat,
  'thirdPrizeRatio' : IDL.Nat,
  'drawInterval' : DrawInterval,
});
export const CreateLotteryError = IDL.Variant({
  'invalidTicketConfig' : IDL.Null,
  'invalidPrizeConfig' : IDL.Null,
  'invalidDrawTime' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'referralCode' : IDL.Text,
  'isBlocked' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : IDL.Text,
  'blockedAt' : IDL.Opt(Time),
  'email' : IDL.Text,
  'coinsBalance' : IDL.Nat,
  'isVerified' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createLottery' : IDL.Func(
      [CreateLotteryData],
      [IDL.Variant({ 'ok' : LotteryPool, 'err' : CreateLotteryError })],
      [],
    ),
  'getCallerUserProfile' : IDL.Func(
      [],
      [
        IDL.Variant({
          'ok' : UserProfile,
          'err' : IDL.Variant({
            'notFound' : IDL.Null,
            'unauthorized' : IDL.Null,
          }),
        }),
      ],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LotteryType = IDL.Variant({ 'daily' : IDL.Null, 'weekly' : IDL.Null });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const DrawInterval = IDL.Variant({
    'h1' : IDL.Null,
    'h3' : IDL.Null,
    'h5' : IDL.Null,
    'h12' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const CreateLotteryData = IDL.Record({
    'lotteryType' : LotteryType,
    'ticketsPerUserMax' : IDL.Nat,
    'logo' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'firstPrizeRatio' : IDL.Nat,
    'description' : IDL.Text,
    'drawTime' : Time,
    'firstPrizePercent' : IDL.Nat,
    'thirdPrizePercent' : IDL.Nat,
    'maxTickets' : IDL.Nat,
    'secondPrizeRatio' : IDL.Nat,
    'secondPrizePercent' : IDL.Nat,
    'winnerPayoutPercent' : IDL.Nat,
    'ticketPrice' : IDL.Nat,
    'thirdPrizeRatio' : IDL.Nat,
    'drawInterval' : DrawInterval,
  });
  const LotteryStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const LotteryPool = IDL.Record({
    'id' : IDL.Text,
    'status' : LotteryStatus,
    'totalTicketsSold' : IDL.Nat,
    'lotteryType' : LotteryType,
    'ticketsPerUserMax' : IDL.Nat,
    'logo' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'createdAt' : Time,
    'firstPrizeRatio' : IDL.Nat,
    'description' : IDL.Text,
    'drawTime' : Time,
    'firstPrizePercent' : IDL.Nat,
    'thirdPrizePercent' : IDL.Nat,
    'maxTickets' : IDL.Nat,
    'secondPrizeRatio' : IDL.Nat,
    'secondPrizePercent' : IDL.Nat,
    'totalPoolAmount' : IDL.Nat,
    'winnerPayoutPercent' : IDL.Nat,
    'ticketPrice' : IDL.Nat,
    'thirdPrizeRatio' : IDL.Nat,
    'drawInterval' : DrawInterval,
  });
  const CreateLotteryError = IDL.Variant({
    'invalidTicketConfig' : IDL.Null,
    'invalidPrizeConfig' : IDL.Null,
    'invalidDrawTime' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'referralCode' : IDL.Text,
    'isBlocked' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : IDL.Text,
    'blockedAt' : IDL.Opt(Time),
    'email' : IDL.Text,
    'coinsBalance' : IDL.Nat,
    'isVerified' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createLottery' : IDL.Func(
        [CreateLotteryData],
        [IDL.Variant({ 'ok' : LotteryPool, 'err' : CreateLotteryError })],
        [],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [
          IDL.Variant({
            'ok' : UserProfile,
            'err' : IDL.Variant({
              'notFound' : IDL.Null,
              'unauthorized' : IDL.Null,
            }),
          }),
        ],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };