/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateLotteryData {
  'lotteryType' : LotteryType,
  'ticketsPerUserMax' : bigint,
  'logo' : [] | [ExternalBlob],
  'name' : string,
  'firstPrizeRatio' : bigint,
  'description' : string,
  'drawTime' : Time,
  'firstPrizePercent' : bigint,
  'thirdPrizePercent' : bigint,
  'maxTickets' : bigint,
  'secondPrizeRatio' : bigint,
  'secondPrizePercent' : bigint,
  'winnerPayoutPercent' : bigint,
  'ticketPrice' : bigint,
  'thirdPrizeRatio' : bigint,
  'drawInterval' : DrawInterval,
}
export type CreateLotteryError = { 'invalidTicketConfig' : null } |
  { 'invalidPrizeConfig' : null } |
  { 'invalidDrawTime' : null } |
  { 'unauthorized' : null };
export type DrawInterval = { 'h1' : null } |
  { 'h3' : null } |
  { 'h5' : null } |
  { 'h12' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export type ExternalBlob = Uint8Array;
export interface LotteryPool {
  'id' : string,
  'status' : LotteryStatus,
  'totalTicketsSold' : bigint,
  'lotteryType' : LotteryType,
  'ticketsPerUserMax' : bigint,
  'logo' : [] | [ExternalBlob],
  'name' : string,
  'createdAt' : Time,
  'firstPrizeRatio' : bigint,
  'description' : string,
  'drawTime' : Time,
  'firstPrizePercent' : bigint,
  'thirdPrizePercent' : bigint,
  'maxTickets' : bigint,
  'secondPrizeRatio' : bigint,
  'secondPrizePercent' : bigint,
  'totalPoolAmount' : bigint,
  'winnerPayoutPercent' : bigint,
  'ticketPrice' : bigint,
  'thirdPrizeRatio' : bigint,
  'drawInterval' : DrawInterval,
}
export type LotteryStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export type LotteryType = { 'daily' : null } |
  { 'weekly' : null };
export type Time = bigint;
export interface UserProfile {
  'id' : string,
  'referralCode' : string,
  'isBlocked' : boolean,
  'name' : string,
  'createdAt' : Time,
  'role' : string,
  'blockedAt' : [] | [Time],
  'email' : string,
  'coinsBalance' : bigint,
  'isVerified' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createLottery' : ActorMethod<
    [CreateLotteryData],
    { 'ok' : LotteryPool } |
      { 'err' : CreateLotteryError }
  >,
  'getCallerUserProfile' : ActorMethod<
    [],
    { 'ok' : UserProfile } |
      { 'err' : { 'notFound' : null } | { 'unauthorized' : null } }
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];